version: '3.9'

services:
  salesapi:
    image: ${DOCKER_REGISTRY-}salesapi
    container_name: web_api_application
    ports:
     - 5000:80

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server-2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

  
 
